//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class rongzitiaozheng_info
    {
        public int idstr { get; set; }
        public string luruname { get; set; }
        public Nullable<System.DateTime> lurudate { get; set; }
        public string zijinlaiyuan { get; set; }
        public string projectnamebefore { get; set; }
        public Nullable<decimal> projectjinebefore { get; set; }
        public string projectnamenow { get; set; }
        public Nullable<decimal> projectjinenow { get; set; }
        public string remark { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
    }
}
