//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_info
    {
        public int idstr { get; set; }
        public Nullable<int> rodetype { get; set; }
        public string username { get; set; }
        public string loginname { get; set; }
        public string loginpass { get; set; }
        public string rolequanxian { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public Nullable<System.DateTime> updatetime { get; set; }
        public string remark { get; set; }
    }
}
