//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XingLuRongZiServer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class xinglurongziEntities : DbContext
    {
        public xinglurongziEntities()
            : base("name=xinglurongziEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<menueditor_info> menueditor_info { get; set; }
        public DbSet<project_info> project_info { get; set; }
        public DbSet<projectzijin_userinfo> projectzijin_userinfo { get; set; }
        public DbSet<rongzi_info> rongzi_info { get; set; }
        public DbSet<rongzianpai_info> rongzianpai_info { get; set; }
        public DbSet<rongzihuanbenfuxi_info> rongzihuanbenfuxi_info { get; set; }
        public DbSet<rongzitiaozheng_info> rongzitiaozheng_info { get; set; }
        public DbSet<rongzizhihuan_info> rongzizhihuan_info { get; set; }
        public DbSet<user_info> user_info { get; set; }
        public DbSet<userlog_info> userlog_info { get; set; }
    }
}
