//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XingLuRongZiServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class project_info
    {
        public int idstr { get; set; }
        public string projectname { get; set; }
        public string projectdanwei { get; set; }
        public Nullable<decimal> projectzongtou { get; set; }
        public Nullable<System.DateTime> projectstartdate { get; set; }
        public Nullable<System.DateTime> projectcompletedate { get; set; }
        public string prpjecttype { get; set; }
        public string projectstatus { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public Nullable<System.DateTime> updatetime { get; set; }
        public string remark { get; set; }
    }
}
