//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XingLuRongZiServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class projectzijin_userinfo
    {
        public int idstr { get; set; }
        public string lururen { get; set; }
        public Nullable<System.DateTime> lurudate { get; set; }
        public string projectname { get; set; }
        public string zhaiwuname { get; set; }
        public Nullable<decimal> zhaiwujine { get; set; }
        public string zhifuxingzhi { get; set; }
        public Nullable<System.DateTime> zhifudate { get; set; }
        public Nullable<decimal> zhifujine { get; set; }
        public Nullable<System.DateTime> shouhuidate { get; set; }
        public Nullable<decimal> shouhuijine { get; set; }
        public string remark { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
    }
}
