//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XingLuRongZiServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class rongzianpai_info
    {
        public int idstr { get; set; }
        public string luruname { get; set; }
        public Nullable<System.DateTime> lurudate { get; set; }
        public string zhaiwuname { get; set; }
        public string projectname { get; set; }
        public Nullable<decimal> anpaijine1 { get; set; }
        public Nullable<decimal> anpaijine2 { get; set; }
        public Nullable<decimal> anpaijine3 { get; set; }
        public Nullable<System.DateTime> anpaidate { get; set; }
        public Nullable<System.DateTime> yuedate { get; set; }
        public string remark { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
    }
}
