//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XingLuRongZiServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class rongzihuanbenfuxi_info
    {
        public int idstr { get; set; }
        public Nullable<int> fuxiyear { get; set; }
        public string fuxidatetype { get; set; }
        public Nullable<System.DateTime> fuxidate { get; set; }
        public Nullable<int> jixitianshu { get; set; }
        public Nullable<double> nianlilv { get; set; }
        public Nullable<double> feilv { get; set; }
        public Nullable<decimal> daozhangjine { get; set; }
        public Nullable<decimal> huanbenjine { get; set; }
        public Nullable<decimal> benjinyue { get; set; }
        public Nullable<decimal> yingjilixi { get; set; }
        public Nullable<decimal> yingfufeiyong { get; set; }
        public Nullable<int> shifouqingchang { get; set; }
        public string remark { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
    }
}
