//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XingLuRongZiServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class rongzi_info
    {
        public int idstr { get; set; }
        public string zhaiwunrename { get; set; }
        public string zhaiquanrenname { get; set; }
        public string zhaiquanrentype { get; set; }
        public string rongzifangshi { get; set; }
        public string zhaiwutype { get; set; }
        public string zhaiwuname { get; set; }
        public string zijinyongtu { get; set; }
        public Nullable<decimal> hetongjine { get; set; }
        public Nullable<System.DateTime> daoweijineshidian { get; set; }
        public Nullable<System.DateTime> rongziyueshidian { get; set; }
        public string danbaofangshi { get; set; }
        public string lilvtype { get; set; }
        public string lilvmiaoshu { get; set; }
        public Nullable<double> lilvbaifenbi { get; set; }
        public Nullable<double> feilv { get; set; }
        public Nullable<int> qixian { get; set; }
        public Nullable<System.DateTime> qixiri { get; set; }
        public Nullable<System.DateTime> daoqiri { get; set; }
        public string remark { get; set; }
        public string hetongno { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
        public Nullable<System.DateTime> updatetime { get; set; }
        public Nullable<decimal> rongziyue { get; set; }
        public Nullable<decimal> daoweijine { get; set; }
    }
}
