//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace XingLuRongZiServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class userlog_info
    {
        public int idstr { get; set; }
        public string loginname { get; set; }
        public Nullable<int> logtype { get; set; }
        public string logcontent { get; set; }
        public Nullable<System.DateTime> createtime { get; set; }
    }
}
